image: docker:19.03.12

variables:
  # change d-in-d to use unencrpyted to fix bug
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  #CI_DEBUG_TRACE: "true"
  CACHE: "" 

services:
  - docker:19.03.12-dind

stages:
  - check_github_release
  - build
  - push

check_github_release:
  image: piwi3910/base:ubuntu_latest
  tags:
    - DOCKER
    - K8S
    - ARM64
  stage: check_github_release
  script:
    - chmod +x version.sh
    - ./version.sh
  artifacts:
    reports:
      dotenv: vars.env

build:
  tags:
    - DOCKER
    - K8S
    - ARM64
  stage: build
  script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    # fetches the latest image (not failing if image is not found)
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    # notice the cache-from, which is going to use the image we just pulled locally
    # the built image is tagged locally with the commit SHA, and then pushed to 
    # the GitLab registry
    - echo $version
    - >
      docker build
      --pull
      --build-arg SONARR_VERSION=$version
      --cache-from $CI_REGISTRY_IMAGE:latest
      --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      $CACHE
      .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  dependencies:
    - check_github_release

# Here, the goal is to tag the "master" branch as "latest" and version number of sabnzbd
push latest:
  tags:
    - DOCKER
    - K8S
    - ARM64
  variables:
    # We are just playing with Docker here. 
    # We do not need GitLab to clone the source code.
    GIT_STRATEGY: none
  stage: push
  only:
    # Only "master" should be tagged "latest"
    - main
  script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    # Because we have no guarantee that this job will be picked up by the same runner 
    # that built the image in the previous step, we pull it again locally
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    # Then we tag it "latest"
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:$version
    # Annnd we push it.
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$version
  dependencies:
  - check_github_release


# Here, to dockerhub
push latest to Dockerhub:
  tags:
    - DOCKER
    - K8S
    - ARM64
  variables:
    # We are just playing with Docker here. 
    # We do not need GitLab to clone the source code.
    GIT_STRATEGY: none
  stage: push
  only:
    # Only "master" should be tagged "latest"
    - main
  script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    # Because we have no guarantee that this job will be picked up by the same runner 
    # that built the image in the previous step, we pull it again locally
    - docker pull $CI_REGISTRY_IMAGE:latest
    # we now login to our dockerhub
    - docker login -u $dockerhub_user -p $dockerhub_password docker.io
    # retag the image with the dockerhub name
    - docker tag $CI_REGISTRY_IMAGE:latest $dockerhub_user/$dockerhub_image:latest
    - docker tag $CI_REGISTRY_IMAGE:latest $dockerhub_user/$dockerhub_image:$version
    # And we push it.
    - docker push $dockerhub_user/$dockerhub_image:latest
    - docker push $dockerhub_user/$dockerhub_image:$version
  dependencies:
    - check_github_release


# Finally, the goal here is to Docker tag any Git tag
# GitLab will start a new pipeline everytime a Git tag is created, which is pretty awesome
Push tag:
  tags:
    - DOCKER
    - K8S
    - ARM64
  variables:
    # Again, we do not need the source code here. Just playing with Docker.
    GIT_STRATEGY: none
  stage: push
  only:
    # We want this job to be run on tags only.
    - tags
  script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  dependencies:
    - check_github_release

